### ISSUE TITLE
Accept FeatureCollection in geojson extract polygon

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/osmium-tool#72]
Though this may not be the right thing to do, the fact is most geojson generating libraries (i.e. GDAL OGR) do generate `"type": "FeatureCollection"` root element, even if there is only one polygon or multipolygon in `features` array.
Could be great if osmium extract accepts this geojson format, so there won't be any effort to reformat geojson (extract the feature element) to fit the expected osmium format.
It could simply use the first object in `features` array ignoring all the others, if there are more than one feature.
@joto What do you think of it?

**Comment by joto** [comment]
This should work now. Please test.

**Comment by nextstopsun** [comment]
I've tried with latest master and unfortunately still can't set the header.

Setting like this:

```
osmium apply-changes -v --output-header='options.timestamp=2017-08-31T08:58:02Z' my.pbf changes.o5c -o new.pbf -O
```

@joto Could you please add more info on `--output-header` to the docs? (an example, or a list of standard headers) It sends to a libosmium docs so a bit uneasy to find the right place with that info.

**Comment by nextstopsun** [comment]
@joto Thanks a lot!! I'll test this and write back.

**Comment by bkowshik** [comment]
> It could simply use the first object in features array ignoring all the others, if there are more than one feature.

I have just started using `osmium-tool` in my projects. Curious to understand why we don't want to do all features (more than 1 feature) in a `FeatureCollection`?

**Comment by joto** [comment]
@bkowshik Because to use all features we'd have to merge them somehow first. That's a potentially complex geometry operation with possibly overlapping polygons. This is outside the scope of Osmium.
